// repository
export const FETCH_HOME_DATA = 'FETCH_HOME_DATA';
export const FETCH_REPOSITORY_DATA = 'FETCH_REPOSITORY_DATA';
export const CLEAR_REPOSITORY_DATA = 'CLEAR_REPOSITORY_DATA';
export const CHANGE_ICON_SIZE = 'CHANGE_ICON_SIZE';
export const RESET_ICON_SIZE = 'RESET_ICON_SIZE';
export const FETCH_TINY_REPOSITORY = 'FETCH_TINY_REPOSITORY';
export const FETCH_REPOSITORY_LOG = 'FETCH_REPOSITORY_LOG';

// cart
export const INIT_CART = 'INIT_CART';
export const FETCH_CART_DETAIL = 'FETCH_CART_DETAIL';
export const ADD_ICON_TO_CART = 'ADD_ICON_TO_CART';
export const DELETE_ICON_IN_CART = 'DELETE_ICON_IN_CART';
export const TOGGLE_CART_LIST_DISPLAY = 'TOGGLE_CART_LIST_DISPLAY';
export const DUMP_ICON_LOCALSTORGAGE = 'DUMP_ICON_LOCALSTORGAGE';
export const CHANGE_CART_SAVE_TYPE = 'CHANGE_CART_SAVE_TYPE';
//  search
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';

// setting
export const LAUNCH_REDUX_DEVTOOLS = 'LAUNCH_REDUX_DEVTOOLS';

// project
export const FETCH_USERS_PROJECT_INFO = 'FETCH_USERS_PROJECT_INFO';
export const CHOSE_PROJECT_FOR_SAVE = 'CHOSE_PROJECT_FOR_SAVE';
export const SAVE_TO_PROJECT = 'SAVE_TO_PROJECT';

// notification
export const FETCH_ALL_INFO = 'FETCH_ALL_INFO';
export const FETCH_SYSTEM_INFO = 'FETCH_SYSTEM_INFO';
export const FETCH_PROJECT_INFO = 'FETCH_PROJECT_INFO';

// uploaded
export const FETCH_MY_LOADED = 'FETCH_MY_LOADED';
export const DELETE_ICON = 'DELETE_ICON';
// upload
export const FETCH_UPLOAD_ICON = 'FETCH_UPLOAD_ICON';
// uploadEdit
export const FETCH_SUBMIT_ICON = 'FETCH_SUBMIT_ICON';

// user
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const LOGOUT_DESTORY = 'LOGOUT_DESTORY';

// icon
export const FETCH_ICON_DETAIL = 'FETCH_ICON_DETAIL';
export const EDIT_ICON = 'EDIT_ICON';
export const UPLOAD_ICON = 'UPLOAD_ICON';
