// repository
export const FETCH_HOME_DATA = 'FETCH_HOME_DATA';
export const FETCH_REPOSITORY_DATA = 'FETCH_REPOSITORY_DATA';
export const CLEAR_REPOSITORY_DATA = 'CLEAR_REPOSITORY_DATA';
export const CHANGE_ICON_SIZE = 'CHANGE_ICON_SIZE';
export const RESET_ICON_SIZE = 'RESET_ICON_SIZE';
export const FETCH_TINY_REPOSITORY = 'FETCH_TINY_REPOSITORY';
export const FETCH_REPOSITORY_LOG = 'FETCH_REPOSITORY_LOG';
export const FETCH_REPOS = 'FETCH_REPOS';
export const UPDATE_REPO_OWNER = 'UPDATE_REPO_OWNER';
export const CREATE_REPO = 'CREATE_REPO';

// cart
export const INIT_CART = 'INIT_CART';
export const FETCH_CART_DETAIL = 'FETCH_CART_DETAIL';
export const ADD_ICON_TO_CART = 'ADD_ICON_TO_CART';
export const DELETE_ICON_IN_CART = 'DELETE_ICON_IN_CART';
export const TOGGLE_CART_LIST_DISPLAY = 'TOGGLE_CART_LIST_DISPLAY';
export const DUMP_ICON_LOCALSTORAGE = 'DUMP_ICON_LOCALSTORAGE';
//  search
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
export const FETCH_SEARCH_REPOS = 'FETCH_SEARCH_REPOS';
export const FETCH_SEARCH_PROJECTS = 'FETCH_SEARCH_PROJECTS';

// setting
export const LAUNCH_REDUX_DEVTOOLS = 'LAUNCH_REDUX_DEVTOOLS';

// project
export const FETCH_USERS_PROJECT_LIST = 'FETCH_USERS_PROJECT_LIST';
export const FETCH_ALL_PROJECT = 'FETCH_ALL_PROJECT';
export const FETCH_USERS_PROJECT_INFO = 'FETCH_USERS_PROJECT_INFO';
export const FETCH_PUBLIC_PROJECT_LIST = 'FETCH_PUBLIC_PROJECT_LIST';
export const FETCH_PUBLIC_PROJECT_INFO = 'FETCH_PUBLIC_PROJECT_INFO';
export const CHOSE_PROJECT_FOR_SAVE = 'CHOSE_PROJECT_FOR_SAVE';
export const SAVE_TO_PROJECT = 'SAVE_TO_PROJECT';
export const PATCH_USERS_PROJECT_DETAIL = 'PATCH_USERS_PROJECT_DETAIL';
export const FETCH_MEMBERS_SUGGEST_LIST = 'FETCH_MEMBERS_SUGGEST_LIST';
export const PATCH_PROJECT_MEMBERS = 'PATCH_PROJECT_MEMBERS';
export const FETCH_ALL_VERSION = 'FETCH_ALL_VERSION';
export const TETCH_PROJECT_VERSION = 'TETCH_PROJECT_VERSION';
export const COMPARE_PROJECT_VERSION = 'COMPARE_PROJECT_VERSION';
export const POST_GENERATE_VERSION = 'POST_GENERATE_VERSION';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const FETCH_PROJECT_LOG = 'FETCH_PROJECT_LOG';
export const SAVE_TO_NEW_PROJECT = 'SAVE_TO_NEW_PROJECT';
export const DELETE_PROJECT_ICON = 'DELETE_PROJECT_ICON';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const UPDATE_PROJECT_OWNER = 'UPDATE_PROJECT_OWNER';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const FETCH_HISTORY_PROJECT = 'FETCH_HISTORY_PROJECT';
// notification
export const FETCH_ALL_INFO = 'FETCH_ALL_INFO';
export const FETCH_SYSTEM_INFO = 'FETCH_SYSTEM_INFO';
export const FETCH_PROJECT_INFO = 'FETCH_PROJECT_INFO';
export const FETCH_UNREAD_COUNT = 'FETCH_UNREAD_COUNT';

// uploaded
export const FETCH_MY_LOADED = 'FETCH_MY_LOADED';
export const DELETE_ICON = 'DELETE_ICON';
// upload
export const FETCH_UPLOAD_ICON = 'FETCH_UPLOAD_ICON';
// uploadEdit
export const FETCH_UPLOAD_EDIT_LOAD = 'FETCH_UPLOAD_EDIT_LOAD';
export const FETCH_SUBMIT_EDIT_ICONS = 'FETCH_SUBMIT_EDIT_ICONS';
export const FETCH_UPLOAD_SINGLE_ICON = 'FETCH_UPLOAD_SINGLE_ICON';
// uploadaudit


// user
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const LOGOUT_DESTORY = 'LOGOUT_DESTORY';

// icon
export const FETCH_ICON_DETAIL = 'FETCH_ICON_DETAIL';
export const EDIT_ICON = 'EDIT_ICON';
export const EDIT_ICON_STYLE = 'EDIT_ICON_STYLE';
export const UPLOAD_ICON = 'UPLOAD_ICON';
export const DOWNLOAD_ICONS = 'DOWNLOAD_ICONS';
// workbench
export const FETCH_WORKBENCH_ICONS = 'FETCH_WORKBENCH_ICONS';
export const DELETE_WORKBENCH_ICON = 'DELETE_WORKBENCH_ICON';
export const UPDATE_WORKBENCH = 'UPDATE_WORKBENCH';
export const SELECT_EDIT = 'SELECT_EDIT';
export const UPLOAD_ICONS = 'UPLOAD_ICONS';
export const SELECT_REPO = 'SELECT_REPO';

// auditing
export const FETCH_AUDIT_ICONS = 'FETCH_AUDIT_ICONS';
export const AUDIT_ICONS = 'AUDIT_ICONS';
export const UPDATE_AUDIT_ICONS = 'UPDATE_AUDIT_ICONS';
export const SELECT_AUDIT_ICON = 'SELECT_AUDIT_ICON';
